[general]
live_config_reload = true

[window]
padding = { x = 20, y = 20 }

[font]
normal = { family = "Misc Tamsyn" }
size = 9

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_timeout = 0
