[general]
live_config_reload = true

[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "Misc Tamsyn" }
size = 9

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_timeout = 0

[colors.primary]
foreground = "#eeeeee"
background = "#000000"
